In [1]:
import numpy as np 
import pandas as pd
import math
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
uploded = files.upload()

ModuleNotFoundError: No module named 'google'

In [3]:
import io
df = pd.read_csv(io.BytesIO(uploded['Churn_Modelling.csv']))
df.shape

(10000, 14)

In [4]:
df.drop(['CustomerId','RowNumber','Surname'], axis = 'columns', inplace =True)

In [5]:
df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
df.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [7]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [8]:
#one hot encoding
df = pd.get_dummies(data = df, columns=['Geography'])
df.dtypes

CreditScore            int64
Gender                object
Age                    int64
Tenure                 int64
Balance              float64
NumOfProducts          int64
HasCrCard              int64
IsActiveMember         int64
EstimatedSalary      float64
Exited                 int64
Geography_France       uint8
Geography_Germany      uint8
Geography_Spain        uint8
dtype: object

In [9]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [10]:
df['Gender'].replace(['Male', 'Female'],[1, 0], inplace= True)

In [11]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [12]:
#separate outcome or target col
X = df.drop(['Exited'], axis=1)
y = df['Exited']

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
# feature scaling
#
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
import tensorflow as tf
from tensorflow import keras

In [17]:
model = keras.Sequential([
    keras.layers.Dense(12, input_shape=(12,),activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

In [18]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [19]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5531 - accuracy: 0.7129
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4385 - accuracy: 0.8006
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4247 - accuracy: 0.8123
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4161 - accuracy: 0.8192
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4026 - accuracy: 0.8300
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3836 - accuracy: 0.8411
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3689 - accuracy: 0.8476
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3587 - accuracy: 0.8525
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3527 - accuracy: 0.8549
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3504 - accura

In [20]:
model.evaluate(X_test, y_test)

63/63 [==============================] - 0s 2ms/step - loss: 0.3426 - accuracy: 0.8570


[0.34256526827812195, 0.8569999933242798]

In [21]:
yp = model.predict(X_test)

63/63 [==============================] - 0s 1ms/step


In [22]:
from sklearn.metrics import confusion_matrix , classification_report

In [23]:
y_pred = []
for element in yp:
    if element > 0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)

In [24]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.93      0.91      1595
           1       0.68      0.56      0.61       405

    accuracy                           0.86      2000
   macro avg       0.79      0.75      0.76      2000
weighted avg       0.85      0.86      0.85      2000



In [25]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=y_pred)

In [26]:
cm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1488,  107],
       [ 179,  226]], dtype=int32)>

In [27]:
tf.math.confusion_matrix(labels=y_test,predictions=y_pred)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1488,  107],
       [ 179,  226]], dtype=int32)>